recordTerminator = sprintf('\r\n');
fieldTerminator = ';';
% camera angle 119 degrees


g_enable_car_engine = 0.0;
g_enable_car_steering_wheel = 0.0;
g_enable_emergency_brake = 0.0;
g_enable_pixy_vector_approximation = 0.0;
g_enable_distance_sensor1 = 0.0;
g_enable_distance_sensor2 = 1.0;
g_enable_distance_sensor3 = 0.0;
g_enable_remote_start_stop = 0.0;
g_enable_finish_line_detection = 0;
g_enable_oversteer_mitigation = 01;

g_black_color_treshold = 0.2;
g_lookahead_min_distance_cm = 20.0;                       % 22
g_lookahead_max_distance_cm = 50.0;                       % 40
g_vehicle_min_speed_mps = 0.5;
g_vehicle_max_speed_mps = 3.0;                                      % 
g_car_speed_mps_ki = -0.001;                                      %-0.02;
g_car_speed_mps_kd = 0.0;                                      %-0.2;
g_car_speed_mps_ki_min_max_impact = 5.0;
g_emergency_brake_activation_max_distance_m = 1.5;                     % 75
g_emergency_brake_speed_mps = 0.3;
g_emergency_brake_distance_from_obstacle_m = 0.1;       % 14
g_emergency_brake_enable_delay_s = 0.0;
g_enable_change_aeb_max_distance_after_delay_s = -1.0;
g_steering_wheel_angle_offset_deg = 6.5;            % -4.7;
g_min_x_axis_angle_vector_deg = 15.0;
g_max_speed_after_delay_mps = 0.3;
g_finish_line_angle_tolerance = 30.0;
g_oversteer_mitigation_yaw_tolerance_rad_s = deg2rad(150);
g_oversteer_mitigation_yaw_delta_tolerance_rad_s = deg2rad(360);
g_edf_raw_speed = 180;

g_powertrain_left_wheel_kp = 0.0;
g_powertrain_left_wheel_ki = 0.1;
g_powertrain_left_wheel_kd = 0.0;
g_powertrain_left_wheel_ki_max_sum = 0.4;
g_powertrain_right_wheel_kp = 0.0;
g_powertrain_right_wheel_ki = 0.1;
g_powertrain_right_wheel_kd = 0.0;
g_powertrain_right_wheel_ki_max_sum = 0.4;

g_powertrain_left_wheel_ki = 0.0;
g_powertrain_right_wheel_ki = 0.0;

g_powertrain_left_wheel_ki_max_sum = 0.0;
g_powertrain_right_wheel_ki_max_sum = 0.0;

g_friction_coefficient = 0.9;
g_downward_acceleration = 9.80665;

g_max_acceleration = (g_friction_coefficient * g_downward_acceleration)/2.5;
g_max_deceleration = (g_friction_coefficient * g_downward_acceleration) - 100;


g_camera_offset_y_m = 0.0; %real_value = measured_value - offset    // offset = measured_value - 0

g_max_speed_after_delay_s = 0.0;
g_enable_finish_line_detection_after_delay_s = 0.0;
g_max_speed_after_finish_line_detected_mps = 0.7;


g_line_calibration_data_angle_offset = 0;
g_line_calibration_data_rotation_point_x = 0;
g_line_calibration_data_rotation_point_y = 0;
g_line_calibration_data_x_axis_offset = 0;
g_line_calibration_data_y_axis_offset = 0;

% g_line_calibration_data_angle_offset = 0.028;
% g_line_calibration_data_rotation_point_x = 39.5;
% g_line_calibration_data_rotation_point_y = 26;
% g_line_calibration_data_x_axis_offset = -9.2;
% g_line_calibration_data_y_axis_offset = 0;

g_lane_width_vector_unit = 60.29;    % 51.4
BirdEye_calibration_TrackWidths_upper_segment_A_x = 20.76;  % FL x
BirdEye_calibration_TrackWidths_upper_segment_A_y = 50.64;  % FL y
BirdEye_calibration_TrackWidths_upper_segment_B_x = 53.52;  % FR x
BirdEye_calibration_TrackWidths_upper_segment_B_y = 53.35;  % FR y
BirdEye_calibration_TrackWidths_lower_segment_A_x = 11.38;    % RL x
BirdEye_calibration_TrackWidths_lower_segment_A_y = -2.4;  % RL y
BirdEye_calibration_TrackWidths_lower_segment_B_x = 71.47;  % RR x
BirdEye_calibration_TrackWidths_lower_segment_B_y = 2.47;   % RR y
BirdEye_calibration_valid = 1;

values = [g_lane_width_vector_unit...
    g_lookahead_min_distance_cm...
    g_lookahead_max_distance_cm...
    g_emergency_brake_activation_max_distance_m...
    g_vehicle_min_speed_mps...
    g_vehicle_max_speed_mps...
    g_black_color_treshold...
    g_enable_car_engine...
    g_enable_car_steering_wheel...
    g_emergency_brake_speed_mps...
    g_emergency_brake_distance_from_obstacle_m...
    g_enable_emergency_brake...
    g_enable_pixy_vector_approximation...
    g_enable_distance_sensor1...
    g_enable_distance_sensor2...
    g_emergency_brake_enable_delay_s...
    g_steering_wheel_angle_offset_deg...
    g_enable_distance_sensor3...
    g_min_x_axis_angle_vector_deg...
    g_max_speed_after_delay_mps...
    g_enable_remote_start_stop...
    g_car_speed_mps_ki...
    g_car_speed_mps_kd...
    g_car_speed_mps_ki_min_max_impact...
    g_finish_line_angle_tolerance...
    g_enable_finish_line_detection...
    g_powertrain_left_wheel_kp...
    g_powertrain_left_wheel_ki...
    g_powertrain_left_wheel_kd...
    g_powertrain_left_wheel_ki_max_sum...
    g_powertrain_right_wheel_kp...
    g_powertrain_right_wheel_ki...
    g_powertrain_right_wheel_kd...
    g_powertrain_right_wheel_ki_max_sum...
    g_friction_coefficient...
    g_downward_acceleration...
    g_max_acceleration...
    g_max_deceleration...
    g_line_calibration_data_angle_offset...
    g_line_calibration_data_rotation_point_x...
    g_line_calibration_data_rotation_point_y...
    g_line_calibration_data_x_axis_offset...
    g_line_calibration_data_y_axis_offset...
    g_max_speed_after_delay_s...
    g_enable_finish_line_detection_after_delay_s...
    g_camera_offset_y_m...
    g_max_speed_after_finish_line_detected_mps...
    BirdEye_calibration_TrackWidths_lower_segment_A_x...
    BirdEye_calibration_TrackWidths_lower_segment_A_y...
    BirdEye_calibration_TrackWidths_lower_segment_B_x...
    BirdEye_calibration_TrackWidths_lower_segment_B_y...
    BirdEye_calibration_TrackWidths_upper_segment_A_x...
    BirdEye_calibration_TrackWidths_upper_segment_A_y...
    BirdEye_calibration_TrackWidths_upper_segment_B_x...
    BirdEye_calibration_TrackWidths_upper_segment_B_y...
    BirdEye_calibration_valid...
    g_enable_change_aeb_max_distance_after_delay_s...
    g_enable_oversteer_mitigation...
    g_oversteer_mitigation_yaw_tolerance_rad_s...
    g_oversteer_mitigation_yaw_delta_tolerance_rad_s...
    g_edf_raw_speed];

outputString = '';

for i = 1:length(values)
    outputString = [outputString sprintf('%.3f%c', values(i), fieldTerminator)];
end

if ~isempty(outputString)
    outputString = outputString(1:end-1);
end

outputString = [outputString recordTerminator];
outputString

server.write(outputString, "string")


%45.000;20.000;60.000;0.600;0.300;2.500;0.200;0;0;0.200;0.200;1;0;0;1;0.000;-4.600;0;15.000;2.000;0;-0.020;-0.200;0.300;15.000;0;0.000;0.100;0.000;0.400;0.000;0.100;0.000;0.400;0.550;9.807;-1.000;-1.000;0.000;0.000;0.000;0.000;0.000
%46.500;20.000;60.000;0.350;0.300;1.000;0.200;1.000;0.000;0.200;0.300;0.000;0.000;0.000;1.000;0.000;-4.700;0.000;15.000;0.300;0.000;-0.001;0.000;5.000;15.000;0.000;0.000;0.100;0.000;0.400;0.000;0.100;0.000;0.400;0.700;9.807;6.865;-93.135;0.000;0.000;0.000;0.000;0.000



