recordTerminator = sprintf('\r\n');
fieldTerminator = ';';
% good bad
% 17 - 3
% 22 - 0
g_enable_car_engine = 0.0;
g_enable_car_steering_wheel = 0.0;
g_enable_emergency_brake = 0.0;
g_enable_pixy_vector_approximation = 0.0;             
g_enable_distance_sensor1 = 0.0;
g_enable_distance_sensor2 = 1.0;
g_enable_distance_sensor3 = 0.0;
g_enable_remote_start_stop = 0.0;
g_enable_finish_line_detection = 0;

g_lane_width_vector_unit = 51.5;
g_black_color_treshold = 0.2;
g_lookahead_min_distance_cm = 20.0;                       % 22
g_lookahead_max_distance_cm = 40.0;                       % 40
g_min_speed = 0.5;
g_max_speed = 1.8;                                      % 
g_car_speed_ki = -0.001;                                      %-0.02;
g_car_speed_kd = 0.0;                                      %-0.2;
g_car_speed_ki_min_max_impact = 5.0;
g_emergency_brake_distance_m = 0.6;                     % 75
g_emergency_brake_min_speed = 0.2;
g_emergency_brake_distance_from_obstacle_m = 0.20;       % 14
g_emergency_brake_enable_delay_s = 0.0;
g_steering_wheel_angle_offset_deg = -4.6;
g_min_x_axis_angle_vector = 15.0;
g_max_speed_after_emergency_brake_delay = 0.3;
g_finish_line_angle_tolerance = 15.0;

g_powertrain_left_wheel_kp = 0.0;
g_powertrain_left_wheel_ki = 0.1;
g_powertrain_left_wheel_kd = 0.0;
g_powertrain_left_wheel_ki_max_sum = 0.4;
g_powertrain_right_wheel_kp = 0.0;
g_powertrain_right_wheel_ki = 0.1;
g_powertrain_right_wheel_kd = 0.0;
g_powertrain_right_wheel_ki_max_sum = 0.4;

values = [g_lane_width_vector_unit...
    g_lookahead_min_distance_cm...
    g_lookahead_max_distance_cm...
    g_emergency_brake_distance_m...
    g_min_speed...
    g_max_speed...
    g_black_color_treshold...
    g_enable_car_engine...
    g_enable_car_steering_wheel...
    g_emergency_brake_min_speed...
    g_emergency_brake_distance_from_obstacle_m...
    g_enable_emergency_brake...
    g_enable_pixy_vector_approximation...
    g_enable_distance_sensor1...
    g_enable_distance_sensor2...
    g_emergency_brake_enable_delay_s...
    g_steering_wheel_angle_offset_deg...
    g_enable_distance_sensor3...
    g_min_x_axis_angle_vector...
    g_max_speed_after_emergency_brake_delay...
    g_enable_remote_start_stop...
    g_car_speed_ki...
    g_car_speed_kd...
    g_car_speed_ki_min_max_impact...
    g_finish_line_angle_tolerance...
    g_enable_finish_line_detection...
    g_powertrain_left_wheel_kp...
    g_powertrain_left_wheel_ki...
    g_powertrain_left_wheel_kd...
    g_powertrain_left_wheel_ki_max_sum...
    g_powertrain_right_wheel_kp...
    g_powertrain_right_wheel_ki...
    g_powertrain_right_wheel_kd...
    g_powertrain_right_wheel_ki_max_sum];

outputString = '';

for i = 1:length(values)
    outputString = [outputString sprintf('%.3f%c', values(i), fieldTerminator)];
end

if ~isempty(outputString)
    outputString = outputString(1:end-1);
end

outputString = [outputString recordTerminator];

server.write(outputString, "string")


